export const APP_TEXT = {
  app: {
    name: "TMS Admin",
    tagline: "Real-time transport management, in one dashboard",
  },
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saving: "Saving...",
    close: "Close",
    required: "This field is required",
    invalidNumber: "Enter a valid number",
  },
  nav: {
    dashboard: "Dashboard",
    loads: "Load Management",
    dispatch: "Dispatch",
    drivers: "Drivers",
    fleet: "Fleet",
    tracking: "Tracking",
    billing: "Billing",
    reports: "Reports",
    notifications: "Notifications",
    logout: "Log out",
  },
  login: {
    brandHeadline: "Every truck, every load — one command center.",
    brandSubtext:
      "Dispatch drivers, track deliveries live, and keep billing on autopilot — without switching tabs.",
    featureLive: "Live truck tracking on a map",
    featureDispatch: "One-click load dispatch to drivers",
    featureBilling: "Automatic invoicing and settlements",
    formTitle: "Welcome back",
    formSubtitle: "Sign in to your admin account",
    emailLabel: "Email address",
    emailPlaceholder: "admin@tms.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    showPassword: "Show",
    hidePassword: "Hide",
    submit: "Sign in",
    submitLoading: "Signing in...",
    footerNote: "Admin access only",
    errors: {
      emailRequired: "Email is required",
      emailInvalid: "Enter a valid email address",
      passwordRequired: "Password is required",
      invalidCredentials: "Invalid email or password",
    },
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Live overview of your fleet and operations",
    statActiveTrucks: "Active Trucks",
    statActiveLoads: "Active Loads",
    statDeliveredToday: "Delivered Today",
    statDelayed: "Delayed Loads",
    mapTitle: "Live Fleet Map",
    mapBadgeLive: "Live",
    mapNote: "Connects to real GPS data once drivers go live",
    recentLoadsTitle: "Recent Loads",
    viewAll: "View all",
    alertsTitle: "Alerts",
    noRecentLoads: "No loads yet",
    noAlerts: "No alerts right now",
    table: {
      loadId: "Load ID",
      customer: "Customer",
      route: "Route",
      driver: "Driver",
      status: "Status",
    },
  },
  loads: {
    title: "Load Management",
    subtitle: "Create and manage customer loads",
    newLoad: "New Load",
    searchPlaceholder: "Search by customer, load ID or location",
    filters: {
      all: "All",
      pending: "Pending",
      assigned: "Assigned",
      picked_up: "Picked Up",
      in_transit: "In Transit",
      delivered: "Delivered",
    },
    table: {
      loadId: "Load ID",
      customer: "Customer",
      route: "Route",
      weight: "Weight",
      rate: "Rate",
      driver: "Driver",
      status: "Status",
      created: "Created",
    },
    emptyState: "No loads match this filter",
  },
  search: {
    placeholder: "Search loads, drivers, trucks...",
    noResults: "No results found",
    sectionLoads: "Loads",
    sectionDrivers: "Drivers",
    sectionTrucks: "Trucks",
    hint: "Search across the whole system",
  },
  drivers: {
    title: "Drivers",
    subtitle: "Manage your driver roster and their status",
    addDriver: "Add Driver",
    searchPlaceholder: "Search by name or phone",
    filters: {
      all: "All",
      active: "Active",
      inactive: "Inactive",
    },
    deliveries: "deliveries",
    license: "License",
    phone: "Phone",
    joined: "Joined",
    emptyState: "No drivers match this filter",
  },
  fleet: {
    title: "Fleet",
    subtitle: "Trucks, capacity, and maintenance status",
    addTruck: "Add Truck",
    searchPlaceholder: "Search by truck number or driver",
    filters: {
      all: "All",
      active: "Active",
      maintenance: "Maintenance",
      inactive: "Inactive",
    },
    driver: "Primary Driver",
    lastMaintenance: "Last Maintenance",
    insuranceExpiry: "Insurance Expiry",
    expiresIn: "Expires in",
    expired: "Insurance expired",
    emptyState: "No trucks match this filter",
  },
  dispatch: {
    title: "Dispatch",
    subtitle: "Assign unassigned loads to available drivers",
    unassignedTitle: "Unassigned Loads",
    availableDriversTitle: "Available Drivers",
    statUnassigned: "Unassigned Loads",
    statAvailable: "Available Drivers",
    assign: "Assign",
    assigning: "Assigning...",
    selectDriver: "Select a driver",
    assignedToast: "assigned to",
    allAssigned: "All loads are assigned — nothing pending dispatch",
    noAvailableDrivers: "No drivers available right now",
    onRoute: "On route",
    idle: "Idle",
  },
  tracking: {
    title: "Tracking",
    subtitle: "Live status of every load currently on the road",
    mapTitle: "Live Fleet Map",
    activeLoadsTitle: "Active Loads",
    noActiveLoads: "No loads are currently active",
    stages: {
      assigned: "Assigned",
      picked_up: "Picked Up",
      in_transit: "In Transit",
      delivered: "Delivered",
    },
  },
  billing: {
    title: "Billing",
    subtitle: "Customer invoices and driver settlements",
    statTotalRevenue: "Total Revenue",
    statPending: "Pending Amount",
    statPaidInvoices: "Paid Invoices",
    statPendingSettlements: "Pending Settlements",
    invoicesTitle: "Customer Invoices",
    settlementsTitle: "Driver Settlements",
    searchPlaceholder: "Search by invoice, customer or load ID",
    filters: {
      all: "All",
      paid: "Paid",
      unpaid: "Unpaid",
    },
    table: {
      invoiceId: "Invoice",
      loadId: "Load ID",
      customer: "Customer",
      amount: "Amount",
      status: "Status",
      date: "Date",
      driver: "Driver",
      action: "Action",
    },
    emptyState: "No invoices match this filter",
    exportInvoices: "Export Invoices",
    markPaid: "Mark Paid",
    markPaidConfirmTitle: "Mark as paid?",
  },
  reports: {
    title: "Reports",
    subtitle: "Revenue and performance at a glance",
    statTotalRevenue: "Total Revenue (30d)",
    statOnTimeRate: "On-Time Delivery",
    statAvgRate: "Avg. Rate per Load",
    statTotalDeliveries: "Total Deliveries",
    revenueChartTitle: "Revenue — Last 7 Days",
    topDriversTitle: "Top Drivers by Deliveries",
    exportReport: "Export Report",
  },
  notifications: {
    title: "Notifications",
    subtitle: "Alerts and updates across your fleet",
    markAllRead: "Mark all as read",
    filters: {
      all: "All",
      unread: "Unread",
    },
    emptyState: "No notifications",
  },
} as const;
