export const APP_TEXT = {
  app: {
    name: "B2B TMT Admin",
    tagline: "Real-time transport management, in one dashboard",
  },
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    saving: "Saving...",
    close: "Close",
    required: "This field is required",
    invalidNumber: "Enter a valid number",
  },
  nav: {
    dashboard: "Dashboard",
    loads: "Load Management",
    dispatch: "Dispatch",
    drivers: "Drivers",
    fleet: "Fleet",
    tracking: "Tracking",
    billing: "Billing",
    reports: "Reports",
    notifications: "Notifications",
    customers: "Customers",
    expenses: "Expenses",
    team: "Team",
    logout: "Log out",
  },
  login: {
    brandHeadline: "Every truck, every load — one command center.",
    brandSubtext:
      "Dispatch drivers, track deliveries live, and keep billing on autopilot — without switching tabs.",
    featureLive: "Live truck tracking on a map",
    featureDispatch: "One-click load dispatch to drivers",
    featureBilling: "Automatic invoicing and settlements",
    formTitle: "Welcome back",
    formSubtitle: "Sign in to your admin account",
    emailLabel: "Email address",
    emailPlaceholder: "admin@tms.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    showPassword: "Show",
    hidePassword: "Hide",
    submit: "Sign in",
    submitLoading: "Signing in...",
    footerNote: "Admin access only",
    errors: {
      emailRequired: "Email is required",
      emailInvalid: "Enter a valid email address",
      passwordRequired: "Password is required",
      invalidCredentials: "Invalid email or password",
    },
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Live overview of your fleet and operations",
    statActiveTrucks: "Active Trucks",
    statActiveLoads: "Active Loads",
    statDeliveredToday: "Delivered Today",
    statDelayed: "Delayed Loads",
    mapTitle: "Live Fleet Map",
    mapBadgeLive: "Live",
    mapNote: "Connects to real GPS data once drivers go live",
    recentLoadsTitle: "Recent Loads",
    viewAll: "View all",
    alertsTitle: "Alerts",
    noRecentLoads: "No loads yet",
    noAlerts: "No alerts right now",
    table: {
      loadId: "Load ID",
      customer: "Customer",
      route: "Route",
      driver: "Driver",
      status: "Status",
    },
  },
  loads: {
    title: "Load Management",
    subtitle: "Create and manage customer loads",
    newLoad: "New Load",
    searchPlaceholder: "Search by customer, load ID or location",
    filters: {
      all: "All",
      pending: "Pending",
      assigned: "Assigned",
      picked_up: "Picked Up",
      in_transit: "In Transit",
      delivered: "Delivered",
    },
    table: {
      loadId: "Load ID",
      customer: "Customer",
      route: "Route",
      weight: "Weight",
      rate: "Rate",
      driver: "Driver",
      status: "Status",
      created: "Created",
      actions: "Actions",
    },
    emptyState: "No loads match this filter",
    loadTabs: {
      active: "Active",
      planning: "Planning",
      readyForAccounting: "Ready for Accounting",
      all: "All Loads",
      cancelled: "Cancelled",
    },
    loadActions: {
      menuLabel: "Row actions",
      copyLoad: "Copy Load",
      archiveLoad: "Archive Load",
      cancelLoad: "Cancel Load",
      logCheckCall: "Log Check Call",
      viewLoadLog: "View Load Log",
      sendToAccounting: "Send to Accounting",
      invoiceCreatedToast: "Invoice created and sent to Billing",
      copiedToast: "Load duplicated",
      archivedToast: "Load archived",
      cancelledToast: "Load cancelled",
      cancelConfirmTitle: "Cancel load?",
      cancelConfirmMessage: "This marks the load as cancelled. This cannot be undone.",
      checkCallTitle: "Log Check Call",
      checkCallSubtitle: "Add a status note for this load",
      checkCallNoteLabel: "Note",
      checkCallNotePlaceholder: "e.g. Crossed toll, on schedule",
      checkCallSubmit: "Log Check Call",
      checkCallLoggedToast: "Check call logged",
      loadLogTitle: "Load Log",
      loadLogSubtitlePrefix: "Timeline for",
      loadLogStatusPrefix: "Status:",
      loadLogEmpty: "No check calls logged for this load yet",
    },
    loadTemplates: {
      label: "Use Template",
      noneOption: "— none —",
    },
    customerSelect: {
      label: "Customer",
      placeholder: "Select a customer",
      addNewOption: "+ Add New Customer",
    },
  },
  search: {
    placeholder: "Search loads, drivers, trucks...",
    noResults: "No results found",
    sectionLoads: "Loads",
    sectionDrivers: "Drivers",
    sectionTrucks: "Trucks",
    hint: "Search across the whole system",
  },
  drivers: {
    title: "Drivers",
    subtitle: "Manage your driver roster and their status",
    addDriver: "Add Driver",
    searchPlaceholder: "Search by name or phone",
    filters: {
      all: "All",
      active: "Active",
      inactive: "Inactive",
    },
    deliveries: "deliveries",
    license: "License",
    phone: "Phone",
    joined: "Joined",
    emptyState: "No drivers match this filter",
  },
  fleet: {
    title: "Fleet",
    subtitle: "Trucks, capacity, and maintenance status",
    addTruck: "Add Truck",
    searchPlaceholder: "Search by truck number or driver",
    filters: {
      all: "All",
      active: "Active",
      maintenance: "Maintenance",
      inactive: "Inactive",
    },
    driver: "Primary Driver",
    lastMaintenance: "Last Maintenance",
    insuranceExpiry: "Insurance Expiry",
    expiresIn: "Expires in",
    expired: "Insurance expired",
    emptyState: "No trucks match this filter",
  },
  dispatch: {
    title: "Dispatch",
    subtitle: "Assign unassigned loads to available drivers",
    unassignedTitle: "Unassigned Loads",
    availableDriversTitle: "Available Drivers",
    statUnassigned: "Unassigned Loads",
    statAvailable: "Available Drivers",
    assign: "Assign",
    assigning: "Assigning...",
    selectDriver: "Select a driver",
    assignedToast: "assigned to",
    allAssigned: "All loads are assigned — nothing pending dispatch",
    noAvailableDrivers: "No drivers available right now",
    onRoute: "On route",
    idle: "Idle",
  },
  tracking: {
    title: "Tracking",
    subtitle: "Live status of every load currently on the road",
    mapTitle: "Live Fleet Map",
    activeLoadsTitle: "Active Loads",
    noActiveLoads: "No loads are currently active",
    stages: {
      assigned: "Assigned",
      picked_up: "Picked Up",
      in_transit: "In Transit",
      delivered: "Delivered",
    },
  },
  billing: {
    title: "Billing",
    subtitle: "Customer invoices and driver settlements",
    statTotalRevenue: "Total Revenue",
    statPending: "Pending Amount",
    statPaidInvoices: "Paid Invoices",
    statPendingSettlements: "Pending Settlements",
    invoicesTitle: "Customer Invoices",
    settlementsTitle: "Driver Settlements",
    searchPlaceholder: "Search by invoice, customer or load ID",
    filters: {
      all: "All",
      paid: "Paid",
      unpaid: "Unpaid",
    },
    table: {
      invoiceId: "Invoice",
      loadId: "Load ID",
      customer: "Customer",
      amount: "Amount",
      status: "Status",
      date: "Date",
      driver: "Driver",
      action: "Action",
    },
    emptyState: "No invoices match this filter",
    exportInvoices: "Export Invoices",
    markPaid: "Mark Paid",
    markPaidConfirmTitle: "Mark as paid?",
  },
  reports: {
    title: "Reports",
    subtitle: "Revenue and performance at a glance",
    statTotalRevenue: "Total Revenue (30d)",
    statOnTimeRate: "On-Time Delivery",
    statAvgRate: "Avg. Rate per Load",
    statTotalDeliveries: "Total Deliveries",
    statNetProfit: "Net Profit",
    revenueChartTitle: "Revenue — Last 7 Days",
    topDriversTitle: "Top Drivers by Deliveries",
    exportReport: "Export Report",
  },
  notifications: {
    title: "Notifications",
    subtitle: "Alerts and updates across your fleet",
    markAllRead: "Mark all as read",
    filters: {
      all: "All",
      unread: "Unread",
    },
    emptyState: "No notifications",
    viewAll: "View all",
  },
  customers: {
    title: "Customers",
    subtitle: "Manage the customers you haul loads for",
    addCustomer: "Add Customer",
    searchPlaceholder: "Search by customer name",
    statTotal: "Total Customers",
    statNet30: "Net 30 Terms",
    table: {
      name: "Name",
      contactPerson: "Contact Person",
      phone: "Phone",
      email: "Email",
      paymentTerms: "Payment Terms",
    },
    emptyState: "No customers match your search",
  },
  expenses: {
    title: "Expenses",
    subtitle: "Track fuel, tolls, maintenance and other fleet costs",
    addExpense: "Add Expense",
    searchPlaceholder: "Search by truck number or notes",
    statTotal: "Total Expenses",
    statFuel: "Fuel",
    statMaintenance: "Maintenance",
    statInsurance: "Insurance",
    filters: {
      all: "All",
      Fuel: "Fuel",
      Tolls: "Tolls",
      Maintenance: "Maintenance",
      Insurance: "Insurance",
      Other: "Other",
    },
    table: {
      date: "Date",
      category: "Category",
      truck: "Truck",
      amount: "Amount",
      notes: "Notes",
    },
    emptyState: "No expenses match this filter",
  },
  team: {
    title: "Team",
    subtitle: "Manage who has access to this admin dashboard",
    inviteMember: "Invite Team Member",
    table: {
      name: "Name",
      email: "Email",
      role: "Role",
      status: "Status",
    },
    roles: {
      Admin: "Admin",
      Dispatcher: "Dispatcher",
      Accountant: "Accountant",
    },
    statuses: {
      Active: "Active",
      Invited: "Invited",
    },
    emptyState: "No team members yet",
    invitedToast: "Invitation sent",
  },
  legal: {
    backToLogin: "Back to login",
    lastUpdated: "Last updated",
    lastUpdatedDate: "1 September 2026",
  },
  privacyPolicy: {
    title: "Privacy Policy",
    sections: [
      {
        heading: "1. Information we collect",
        body: "We collect your name, phone number, license details, and truck assignment to operate your driver account. While you are on duty, we collect live location data to power load tracking and route features.",
      },
      {
        heading: "2. How we use your information",
        body: "Your information is used to assign loads, track deliveries, calculate settlements, and communicate trip updates. Location data is only collected while you are actively on a shift.",
      },
      {
        heading: "3. Data sharing",
        body: "Your live location and load status are shared with your fleet admin and the relevant customer for the duration of an active delivery. We do not sell your personal data to third parties.",
      },
      {
        heading: "4. Data retention",
        body: "Trip history, settlements, and delivery records are retained for as long as your driver account is active, and for a reasonable period afterward for accounting and compliance purposes.",
      },
      {
        heading: "5. Your rights",
        body: "You can request a copy of your data or ask for your account to be deleted at any time from the Account screen. Deletion requests are reviewed by your fleet administrator.",
      },
      {
        heading: "6. Contact us",
        body: "For any privacy-related questions, reach out to us on the Support page.",
      },
    ],
  },
  termsOfService: {
    title: "Terms of Service",
    sections: [
      {
        heading: "1. Acceptance of terms",
        body: "By using this driver app, you agree to operate your vehicle safely, follow all applicable transport regulations, and keep your load and delivery status accurate and up to date.",
      },
      {
        heading: "2. Account access",
        body: "Driver accounts are created and managed by your fleet administrator. You are responsible for keeping your login credentials confidential.",
      },
      {
        heading: "3. Use of the app",
        body: "The app is provided to help you manage assigned loads, log duty status, and track routes. Misuse of the app, including falsifying delivery or duty status records, may result in account suspension.",
      },
      {
        heading: "4. Location tracking",
        body: "While on duty, the app shares your live location with your fleet admin to support dispatch and tracking. You can review this in the Privacy Policy.",
      },
      {
        heading: "5. Liability",
        body: "This app assists with logistics coordination but does not replace your responsibility to drive safely and comply with all traffic and transport laws.",
      },
      {
        heading: "6. Changes to these terms",
        body: "These terms may be updated from time to time. Continued use of the app after changes are published constitutes acceptance of the updated terms.",
      },
    ],
  },
  support: {
    title: "Support",
    subtitle: "We usually reply within a few hours",
    phoneLabel: "Phone",
    phoneValue: "+91 11 4000 1234",
    emailLabel: "Email",
    emailValue: "support@tmsdriver.com",
    hoursLabel: "Hours",
    hoursValue: "Mon–Sat, 9 AM – 7 PM IST",
  },
} as const;
